name: Build Services

on:
  workflow_call:
    inputs:
      services:
        description: 'List of services to build'
        required: true
        type: string
        default: sample

jobs:
  matrix_config:
    name: Get matrix config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/data-format-converter-action@main
        name: Get matrix config
        id: yaml2json
        with:
          input: './.scripts/services_matrix_config.yaml'
          from: 'yaml'
          to: 'json'
      - name: Print yaml2json result
        run: echo "${{ steps.yaml2json.outputs.output }}"
        continue-on-error: false
    outputs:
      matrix-config: ${{ steps.yaml2json.outputs.stdout }}

  reusable-job:
    name: Reusable workflow job for services
    runs-on: ubuntu-latest
    steps:
      - name: Get services parameter
        run: |
          echo "Services: ${{ inputs.services }}"

  build-job:
    strategy:
      matrix:
        service: ${{ inputs.services }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "${{ steps.yaml2json.outputs.output }}"
          # for key in ${{ inputs.services }}; do
          #   echo "$key ${{ matrix.services.key }}"
          # done
          # # echo "ECS_SERVICE=${{ matrix.ECS_SERVICE }}"
          # # echo "PROJECT_NAME=${{ matrix.PROJECT_NAME }}"
          # # echo "SERVICE_PATH=${{ matrix.SERVICE_PATH }}"

  # build:
  #   strategy:
  #     matrix:
  #       service: '${{ toJSON(file.path('./.scripts/services_matrix_config.yaml')) }}'
  #       #matrix-config: '${{ toJSON(fromFile(".scripts/services_matrix_config.yml")) }}'
  #       include:
  #         - service: ${{fromJson(inputs.services)}}
  #           build: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code # ???
  #       uses: actions/checkout@v2
  #     - name: Build Service
  #       if: matrix.build == 'true'
  #       run: |
  #         echo "Building ${{ matrix.service.ECS_SERVICE }}"
  #         echo "Using project name: ${{ matrix.service.PROJECT_NAME }}"
  #         echo "Using service path: ${{ matrix.service.SERVICE_PATH }}"
