name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  calling-job:
    name: Call reusable workflow for services
    uses: ./.github/workflows/matrix_build.yaml
    with:
      services: '["api-1", "api-3"]'
