name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  buildConfiguration: '${{ secrets.SOME_SECRET }}'

jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  only-branch-test-job:
    name: branch-test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.buildConfiguration }}

  reused-job:
    name: test-reused-job
    #uses: ./.github/workflows/reuse.yaml
    uses: kayamuskas/workflows/.github/workflows/reuse.yaml@main
    #with:
      #secret: ${{ vars.ENV_OUTSIDE }}
    #secrets: inherit
    secrets:
      SECRET_KEY: ${{ env.buildConfiguration }}

  calling-job:
    needs: [setup]
    name: Call reusable workflow for services
    uses: ./.github/workflows/matrix_build.yaml
    with:
      services: '["api-1",
                  "api-3"
        ]'
