name: Test maxtrix re-use action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  calling-job:
    name: Call reusable workflow for services
    uses: kayamuskas/workflows/.github/workflows/matrix_build.yaml@main
    with:
      services: '["api-1", "api-3"]'
