name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  #buildConfiguration: '${{ secrets.SOME_SECRET }}'
  buildConfiguration: 'tipa release'

jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  only-branch-test-job:
    environment: env_2
    name: branch-test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.buildConfiguration }}
      - run: "echo var for env2 is: ${{ vars.ENV_VAR }}"
      - run: echo ${{ vars.ENV_OUTSIDE }}

  reused-job:
    #environment: env_2
    #runs-on: ubuntu-latest
    name: test-reused-job
    #uses: ./.github/workflows/reuse.yaml
    uses: kayamuskas/workflows/.github/workflows/reuse.yaml@main
    with:
      environment: env_1
     # test_secret: "${{ env.buildConfiguration }}" # <- here's bug
      #test_secret: "just test"
    #secrets: inherit
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #secrets:
     # SECRET_KEY: $buildConfiguration
      #SECRET_KEY: ${{ env.buildConfiguration }}
      #SECRET_KEY: ${{ secrets.SOME_SECRET }}

  calling-job:
    needs: [setup]
    name: Call reusable workflow for services
    uses: ./.github/workflows/matrix_build.yaml
    with:
      services: '["api-1",
                  "api-3"
        ]'
