name: Test maxtrix re-use action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    build_services:
      runs-on: ubuntu-latest
      steps:
        - name: Call reusable workflow for services
          uses: kayamuskas/workflows/.github/workflows/matrix_build.yaml@main
          with:
            services: '["api-1", "api-3"]'
  