name: Deploy DEV or QA

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
#      environment:
#        type: choice
#        description: "Environment to deploy"
#        required: true
#        default: "env_1"
#        options:
#          - env_1
#          - env_2
      app_version:
        description: "Docker image tag to deploy, if empty will build new version"
        required: false
        default: ""

  push:
    branches:
      - main

env:
  #buildConfiguration: '${{ secrets.SOME_SECRET }}'
  buildConfiguration: 'tipa release'

jobs:
  calling_job:
    name: Call reusable workflow for services
    uses: kayamuskas/workflows/.github/workflows/reuse.yaml@main
    with:
      #services: ${{ matrix.services }}}
      environment: env_1
      services: '${{ toJson("api-1, api-2")}}'
      services: '{ "services": { "api-1": "1", "api-2": "2" }}'
#      services:
#        - api-1
#        - api-3
