name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  reused-job:
    name: test-reused-job
    #uses: ./.github/workflows/reuse.yaml
    uses: kayamuskas/workflows/.github/workflows/reuse.yaml@main

  calling-job:
    needs: [setup]
    name: Call reusable workflow for services
    uses: ./.github/workflows/matrix_build.yaml
    with:
      services: '["api-1",
                  "api-3"
        ]'
